### ISSUE TITLE
Incorporate Python3 & Windows support

### ISSUE THREAD

**Issue by petri** [andreikop/python-ws-discovery#4]
@Climax777 and @tran-wang and have forks that implement those. Could we incorporate the forks here?

**Comment by Climax777** [comment]
Mine successfully runs. But for my scenario the library doesn't work with
my onvif cameras (python 2 and 3) so I've not looked at it again.

**Comment by Climax777** [comment]
Also I'm not sure that my fork works for python 2

**Comment by petri** [comment]
@Climax777 I am curious - can you share how/why it doesn't work for your cameras?

**Comment by Climax777** [comment]
@petri the library crashes due to something going wrong and causing:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner                                                                                                                                             
    self.run()                                                                                                                                                                                                       
  File "WSDiscovery.py", line 923, in run                                                                                                                                                                            
    self._recvMessages()                                                                                                                                                                                             
  File "WSDiscovery.py", line 935, in _recvMessages                                                                                                                                                                  
    env = parseEnvelope(data, addr[0])                                                                                                                                                                               
  File "WSDiscovery.py", line 641, in parseEnvelope                                                                                                                                                                  
    return parseHelloMessage(dom)                                                                                                                                                                                    
  File "WSDiscovery.py", line 587, in parseHelloMessage                                                                                                                                                              
    env.setEPR(dom.getElementsByTagNameNS(NS_A, "Address")[0].firstChild.data.strip())                                                                                                                               
IndexError: list index out of range  
```

Just tried it again, it worked the first and second time. Third time failed as above.

**Comment by petri** [comment]
I see. Looks like perhaps `dom.getElementsByTagNameNS` fails to find any "Address" elements in the 'Hello' message, returning empty list. I don't know if the WS-Discovery 'Hello' is always supposed to have a 'Address' element? Or maybe the received message is not really a Hello but something else, or maybe the camera is diverging from the standard, who knows...?

**Comment by hlamer** [comment]
... or maybe it was an answer not from a camera but from some other device in the network

**Comment by hlamer** [comment]
Incorporating forks would be cool!

**Comment by Climax777** [comment]
You are absolutely correct. There was a printer on the network as well. But
at least it shouldn't crash then?

**Comment by petri** [comment]
@Climax777 could you add `import pdb; pdb.set_trace()`to `parseHelloMessage` function (just before the `env.setEPR` call that fails), and take a look what kind of message has been received? Using `dom.toprettyxml()` will give you a nice output.

Then we'll know what's wrong.

**Comment by Climax777** [comment]
```
<?xml version="1.0" ?>
<s:Envelope xmlns:a="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:d="http://schemas.xmlsoap.org/ws/2005/04/discovery" xmlns:qmOYmhBVbK="abc" xmlns:s="http://www.w3.org/2003/05/soap-envelope">
        <s:Header>
                <a:Action>http://schemas.xmlsoap.org/ws/2005/04/discovery/Hello</a:Action>
                <a:MessageID>urn:uuid:1662f2b6-62f1-40a5-9021-3e13cac6bc91</a:MessageID>
                <a:To>urn:schemas-xmlsoap-org:ws:2005:04:discovery</a:To>
                <d:AppSequence InstanceId="1111990001" MessageNumber="1"/>
        </s:Header>
        <s:Body>
                <d:Hello>
                        <a:EndpointReference>
                                <a:Address>urn:uuid:6f1d487b-d438-4708-b9c2-e860b399314c</a:Address>
                        </a:EndpointReference>
                        <d:Types>qmOYmhBVbK:def</d:Types>
                        <d:Scopes>http://other_scope</d:Scopes>
                        <d:XAddrs>localhost:8080/abc 192.168.1.109/device_service 172.17.0.1/device_service</d:XAddrs>
                        <d:MetadataVersion>1</d:MetadataVersion>
                </d:Hello>
        </s:Body>
</s:Envelope>
```

versus a broken one: 

```
<?xml version="1.0" ?>
<SOAP-ENV:Envelope xmlns:SOAP-ENC="http://www.w3.org/2003/05/soap-encoding" xmlns:SOAP-ENV="http://www.w3.org/2003/05/soap-envelope" xmlns:d="http://schemas.xmlsoap.org/ws/2005/04/discovery" xmlns:dn="http://www.onvif.org/ver10/network/wsdl" xmlns:dndl="http://www.onvif.org/ver10/network/wsdl/DiscoveryLookupBinding" xmlns:dnrd="http://www.onvif.org/ver10/network/wsdl/RemoteDiscoveryBinding" xmlns:ns1="http://www.w3.org/2005/05/xmlmime" xmlns:ns10="http://www.onvif.org/ver10/replay/wsdl" xmlns:ns11="http://www.onvif.org/ver10/search/wsdl" xmlns:ns13="http://www.onvif.org/ver20/analytics/wsdl/RuleEngineBinding" xmlns:ns14="http://www.onvif.org/ver20/analytics/wsdl/AnalyticsEngineBinding" xmlns:ns15="http://www.onvif.org/ver10/events/wsdl/PullPointSubscriptionBinding" xmlns:ns16="http://www.onvif.org/ver10/events/wsdl/EventBinding" xmlns:ns17="http://www.onvif.org/ver10/events/wsdl/SubscriptionManagerBinding" xmlns:ns18="http://www.onvif.org/ver10/events/wsdl/NotificationProducerBinding" xmlns:ns19="http://www.onvif.org/ver10/events/wsdl/NotificationConsumerBinding" xmlns:ns2="http://docs.oasis-open.org/wsrf/bf-2" xmlns:ns20="http://www.onvif.org/ver10/events/wsdl/PullPointBinding" xmlns:ns21="http://www.onvif.org/ver10/events/wsdl/CreatePullPointBinding" xmlns:ns22="http://www.onvif.org/ver10/events/wsdl/PausableSubscriptionManagerBinding" xmlns:ns3="http://www.onvif.org/ver10/analyticsdevice/wsdl" xmlns:ns4="http://www.onvif.org/ver10/deviceIO/wsdl" xmlns:ns5="http://www.onvif.org/ver10/display/wsdl" xmlns:ns7="http://docs.oasis-open.org/wsrf/r-2" xmlns:ns8="http://www.onvif.org/ver10/receiver/wsdl" xmlns:ns9="http://www.onvif.org/ver10/recording/wsdl" xmlns:tan="http://www.onvif.org/ver20/analytics/wsdl" xmlns:tds="http://www.onvif.org/ver10/device/wsdl" xmlns:ter="http://www.onvif.org/ver10/error" xmlns:tev="http://www.onvif.org/ver10/events/wsdl" xmlns:timg="http://www.onvif.org/ver20/imaging/wsdl" xmlns:tns1="http://www.onvif.org/ver10/topics" xmlns:tnsn="http://www.eventextension.com/2011/event/topics" xmlns:tptz="http://www.onvif.org/ver20/ptz/wsdl" xmlns:trt="http://www.onvif.org/ver10/media/wsdl" xmlns:tt="http://www.onvif.org/ver10/schema" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:wsa5="http://www.w3.org/2005/08/addressing" xmlns:wsnt="http://docs.oasis-open.org/wsn/b-2" xmlns:wstop="http://docs.oasis-open.org/wsn/t-1" xmlns:xop="http://www.w3.org/2004/08/xop/include" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
        <SOAP-ENV:Header>
                <wsa:MessageID>urn:uuid:ae49d898-f2c2-4412-880b-b8c2b1ff360c</wsa:MessageID>
                <wsa:To SOAP-ENV:mustUnderstand="true">urn:schemas-xmlsoap-org:ws:2005:04:discovery</wsa:To>
                <wsa:Action SOAP-ENV:mustUnderstand="true">http://schemas.xmlsoap.org/ws/2005/04/discovery/Hello</wsa:Action>
        </SOAP-ENV:Header>
        <SOAP-ENV:Body>
                <dn:HelloResponse>
                        <wsa:EndpointReference/>
                </dn:HelloResponse>
        </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```

followed by error: 
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "WSDiscovery.py", line 924, in run
    self._recvMessages()
  File "WSDiscovery.py", line 936, in _recvMessages
    env = parseEnvelope(data, addr[0])
  File "WSDiscovery.py", line 642, in parseEnvelope
    return parseHelloMessage(dom)
  File "WSDiscovery.py", line 588, in parseHelloMessage
    env.setEPR(dom.getElementsByTagNameNS(NS_A, "Address")[0].firstChild.data.strip())
IndexError: list index out of range
```

This is in fact the camera I have to work with...

**Comment by Climax777** [comment]
Doing:

```
nvt = QName("http://www.onvif.org/ver10/network/wsdl", "NetworkVideoTransmitter")
ret = wsd.searchServices(types=[nvt])
```

yields a working response. For some reason, this camera doesn't send a useful response to an empty probe message...G

**Comment by petri** [comment]
@Climax777, just to be sure, are you saying the first SOAP message  is a probe response from one camera and the second a probe response from another camera? I am not familiar at all with the WS-Discovery spec, but it seems strange to me the first one has a `Hello` element vs. the second one has `HelloResponse`...? Do they have a different meaning or can they be used interoperably as a response to a probe?

**Comment by petri** [comment]
Getting back to the topic of Python3 & Windows support:

Given that we've now switched to Python 3, perhaps it would it be better to add an asyncio version  of the networking code? Rather than try to support both a select.poll version and one without it (for Windows) at the same time. Asyncio has a loop for Windows, too.

**Comment by hlamer** [comment]
asyncio is much better than threads

**Comment by andreikop** [comment]
Closing this issue.
Py3 works and there are another issue about Windows support
