### ISSUE TITLE
wsdiscover fails when wireguard vpn is running

### ISSUE THREAD

**Issue by tom24** [andreikop/python-ws-discovery#41]
Setup: ubuntu 18.04, wireguard vpn session active on udp port 51820 (wireguard default).

    $ wsdiscover
    Exception in thread Thread-1:
    Traceback (most recent call last):   
      File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
        self.run()
      File "/usr/local/lib/python3.6/dist-packages/wsdiscovery/threaded.py", line 150, in run
        self._sendPendingMessages()
      File "/usr/local/lib/python3.6/dist-packages/wsdiscovery/threaded.py", line 226, in _sendPendingMessages
        self._sendMsg(msg)
      File "/usr/local/lib/python3.6/dist-packages/wsdiscovery/threaded.py", line 213, in _sendMsg
        sock.sendto(data, (msg.getAddr(), msg.getPort()))
    OSError: [Errno 126] Required key not available

    Discovered:

    $

Temporary fix near line 213 of threaded.py. When patched, good results are obtained even with vpn running.

            for sock in list(self._multiOutUniInSockets.values()):
                # hack to work with wireguard
                try:
                    sock.sendto(data, (msg.getAddr(), msg.getPort()))
                except:
                    pass
                if self._capture:

If the vpn session is stopped, then wsdiscover works without error.

**Comment by andreikop** [comment]
Fixed by #42
